name: Discord Quest Notifications

on:
  issues:
    types: [opened, closed]

jobs:
  quests:
    runs-on: ubuntu-latest
    # Only trigger if the title starts with [Bounty] or [Quest]
    if: ${{ github.event.issue && (startsWith(github.event.issue.title, '[Bounty]') || startsWith(github.event.issue.title, '[Quest]')) }}
    steps:
      - name: Send Issue to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_QUESTS }}
          DISCORD_USERNAME: wb notifs bot
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          DISCORD_CONTENT: |
            ğŸ† **New Quest/Bounty Created**
            ğŸ“Œ Title: ${{ github.event.issue.title }}
            ğŸ“ Description: ${{ github.event.issue.body }}
            

            ${{ github.event.issue.title || github.event.pull_request.title || 'No title' }}
            ğŸ”— [View on GitHub](${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url || github.event.head_commit.url }})
